// <auto-generated />
namespace Telimena.WebApp.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updaterRoundtripWip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updaterRoundtripWip));
        
        string IMigrationMetadata.Id
        {
            get { return "201810121605503_updaterRoundtripWip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
